#cloud-config

package_update: true
package_upgrade: true

packages:
  - qemu-guest-agent
  - docker.io
  - docker-compose-plugin
  - ca-certificates
  - curl
  - bash


runcmd:
  - systemctl enable --now qemu-guest-agent
  - systemctl enable --now docker


### Use ####


# tee /var/lib/vz/snippets/qemu-guest-agent.yml <<EOF
# #cloud-config
# package_update: true
# package_upgrade: true
#
# packages:
#   - qemu-guest-agent
#   - docker.io
#   - docker-compose-plugin
#   - ca-certificates
#   - curl
#   - bash 
#
#
# runcmd:
#   - systemctl enable --now qemu-guest-agent
#   - systemctl enable --now docker
# EOF
#
